### ISSUE TITLE
src/texturegen.js and src/TextureGen.js name conflict

### ISSUE THREAD

**Issue by stianjensen** [sigvef/texturegen#1]
In the `src` folder there are two files called `src/texturegen.js` and `src/TextureGen.js`. HFS+ on OS X isn't case-sensitive, only case-preserving when it comes to file names, and git seems to be really confused by the fact that there are two files called the same thing in this folder.

Should one of them be deleted or renamed?

**Comment by stianjensen** [comment]
#sadface

<img width="772" alt="screenshot 2016-04-17 20 10 13" src="https://cloud.githubusercontent.com/assets/1413267/14589017/6e75142a-04d8-11e6-8696-d83cce4edd3b.png">

**Comment by lionleaf** [comment]
I'm getting several errors, this seems to be one of the main ones, even after trying to make sure there was only one TextureGen.js  (it seems git messed the file up).

Chrome on OSX

:( :( 

<img width="1440" alt="screenshot 2016-04-17 21 29 47" src="https://cloud.githubusercontent.com/assets/610925/14589497/ac406088-04e3-11e6-908b-5088d3bb84f2.png">

**Comment by sigvef** [comment]
I've renamed texturegen.js, so it should work now.

**Comment by stianjensen** [comment]
I don't think git actually did anything to the file, though. I created a work-around and pushed it up: https://github.com/stianjensen/texturegen/tree/osx-workaround

**Comment by stianjensen** [comment]
> I've renamed texturegen.js, so it should work now.

Nice!
