### ISSUE TITLE
Fancy symbols aren't displaying correctly on Mac

### ISSUE THREAD

**Issue by lionleaf** [sigvef/texturegen#2]
<img width="311" alt="screenshot 2016-04-17 22 14 13" src="https://cloud.githubusercontent.com/assets/610925/14589763/319a1dea-04ea-11e6-8175-983f12a881c5.png">

**Comment by lionleaf** [comment]
Doesn't really seem to work either. Here are the reported errors:

<img width="523" alt="screenshot 2016-04-17 22 20 14" src="https://cloud.githubusercontent.com/assets/610925/14589780/92123acc-04ea-11e6-9365-41d1505ea447.png">

**Comment by sigvef** [comment]
Try manually setting the page to uft8 encoding.

**Comment by sigvef** [comment]
see #1 for texturegen errors

**Comment by lionleaf** [comment]
Setting default encoding in chrome to UTF-8 solves it.

**Comment by lionleaf** [comment]
Adding <meta charset=utf8> might be a good idea, though.
