### ISSUE TITLE
Use ES6 style classes

### ISSUE THREAD

**Issue by stianjensen** [sigvef/texturegen#5]
Browser support for ES6 style classes is quite good now ([Classes – mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Browser_compatibility)).

When using lots of class inheritance, and for classes with many methods, the new syntax is more readable imo, so it would be nice to take advantage of it. I'll gladly do the refactoring if you want to.

Example of how it'll look:

```
(function(TextureGen) {
  'use strict';

  class RandomNode extends TextureGen.CanvasNode {
    constructor(id) {
      super(id, 'Random', []);
      this.type = 'RandomNode';
    }

    render() {
      if(!this.dirty) {
        return;
      }

      this.imageData = texturegen.random(this.imageData);
      this.ctx.putImageData(this.imageData, 0, 0);
      this.dirty = false;

      for(var key in this.outputs) {
        this.outputs[key].dirty = true;
        this.outputs[key].render();
      }
    }
  }

  TextureGen.RandomNode = RandomNode;
})(TextureGen);
```

**Comment by sigvef** [comment]
nice
